/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class AppFactory {
  static initialize(astroHandler: (value: any) => any, clientPath: string): AppFactory
  serve(port: number, host?: string | undefined | null): Promise<boolean>
}
